language: ruby
rvm:
  - 1.9.3
before_script:
  - cp spec/db/database.yml.example spec/db/database.yml
  - mysql -e 'create database acts_as_geocodable_plugin_test;'
  - psql -c 'create database acts_as_geocodable_plugin_test;' -U postgres
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true